data = ["Adult New Patient Intake", 
"Would you like to talk to the doctor about any of the following therapies?: multi select, Acupuncture, Nutrition/Weight Management, IV nutrition, Homeopathy, Myotherapy/Bodywork, Herbal Medicine", 
"Occupation: blank", 
"Employer: blank", 
"Employment Status: Full-time, Part-time, Student, Retired", 
"Insurance Plan: blank", 
"Are you: Married, Divorced, Single, Significant partnership, Widowed", 
"Live with: multi select, spouse, parents, children, partner, friends, pets, relatives, alone", 
"Emergency Contact Person: blank", 
"Relation: blank", 
"Address: blank", 
"Home Phone: blank", 
"Cell Phone: blank", 
"What are your health goals?: blank", 
"List all previous health conditions (please include dates): blank", 
"General Health: Excellent, Good, Fair, Poor", 
"Have you had your cholesterol checked?: Yes, No", 
"If yes, Date & Results: blank", 
"Have you had a Pap smear?: Yes, No", 
"if yes, have you ever had an abnormal Pap?: Yes, No", 
"if yes, when and what treatment was provided?: blank", 
"Have you had a mammogram?: Yes, No", 
"If yes, Date & Results: blank", 
"Have you had a bone density test?: Yes, No", 
"If yes, Date & Results: blank", 
"Fatigue/low energy: Y/P", 
"Insomnia: Y/P", 
"Appetite changes: Y/P", 
"Unexplained weight loss/gain: Y/P", 
"Fevers or chills: Y/P", 
"Cold intolerance: Y/P", 
"Heat intolerance: Y/P", 
"Hot flashes: Y/P", 
"Night sweats: Y/P", 
"Sweat too much: Y/P"]

